service: photo-screen

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3000
  webpackIncludeModules: true

functions:
  index:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    
